### ISSUE TITLE
Add title?

### ISSUE THREAD

**Issue by IgorDouven** [JuliaGraphs/GraphPlot.jl#107]
Is there a possibility to add a title to a plot? Also, is there a possibility to specify styling options (e.g., font family)? Either way, it would be good to have something about this in the documentation.

**Comment by dietercastel** [comment]
GraphPlot uses Compose for drawing so an option is to use that as well.
https://giovineitalia.github.io/Compose.jl/latest/gallery/forms/#[text](@ref)-1

**Comment by IgorDouven** [comment]
Thanks, yes I had seen that and tried it but couldn't get it to work. So in
the end I decided I would use tikz to 'stamp' the title on the pdfs that I
had exported. Would be great though if there were more documentation on how
to customize GraphPlot.

Op za 16 mei 2020 om 21:09 schreef Dieter Castel <notifications@github.com>:

**Comment by hdavid16** [comment]
Good feature request
