### ISSUE TITLE
Register and tag package

### ISSUE THREAD

**Issue by AndyGreenwell** [JuliaGraphs/GraphPlot.jl#12]
Can this package be registered and tagged with METADATA.jl such that one does not need to perform `Pkg.clone` to make use of it?

**Comment by sbromberger** [comment]
@afternone please do this! We have it listed in LightGraphs as a plotting option.

**Comment by afternone** [comment]
OK, I'll register it today.

**Comment by sbromberger** [comment]
Checking in - it would be great to be able to `Pkg.add()` this.

**Comment by sbromberger** [comment]
Also - if you want to move it under JuliaGraphs, let me know :)

**Comment by afternone** [comment]
I'm pleased to move it under JuliaGraphs. What should I do?

**Comment by sbromberger** [comment]
Go to the repo settings, under "Danger Zone", select "Transfer", and then the repo name (to confirm) and the organization name (JuliaGraphs). Once it's there I'll set you up with full privs for the repo.

**Comment by sbromberger** [comment]
You'll then want to make sure all links point to the new location of the repo, and then we'll probably need to tag a new version.

**Comment by afternone** [comment]
I received "_You don’t have admin rights to JuliaGraphs_" when transfer the repo.

**Comment by sbromberger** [comment]
Argh. Sorry - I thought I had set up the permissions properly. One sec.

**Comment by sbromberger** [comment]
Ah, you haven't joined the JuliaGraphs team yet. I sent an invite 2 days ago. Could you accept it?

**Comment by afternone** [comment]
Sorry, I think I will receive a notification about the invitation. I have figured out that and accepted the invitation.

**Comment by sbromberger** [comment]
Try now - I'm pretty sure it's ready to go.

**Comment by sbromberger** [comment]
If that doesn't work, you could make me an admin on this project and I can transfer it over. I'm pretty sure we won't need to do that though.

**Comment by afternone** [comment]
I forgot to update the links in document. Can you fix them?

**Comment by sbromberger** [comment]
Sure, I can do this tonight - but you should have full access to the repo. The only thing that should have changed is where it lives.

**Comment by sbromberger** [comment]
I made the change to README.md. I think what you'll want to do is register the package in METADATA.

**Comment by sbromberger** [comment]
OK. Can we register this now? (Do you want me to do it?)

**Comment by afternone** [comment]
I'm glad you doing it.

**Comment by CarloLucibello** [comment]
ref JuliaLang/METADATA.jl#6402. Still no luck with that?

**Comment by sbromberger** [comment]
Haven't had a chance to get back to it. Hopefully today.

**Comment by sbromberger** [comment]
We're tagged at 0.1.0.
