### ISSUE TITLE
Colors 0.11 is out of date

### ISSUE THREAD

**Issue by chakravala** [JuliaGraphs/GraphPlot.jl#121]
The version registered in the package manager uses an outdated `Colors` package.

**Comment by simonschoelly** [comment]
I created a new patch version https://github.com/JuliaRegistries/General/pull/21220 that should fix that. Thanks for reporting!

**Comment by chakravala** [comment]
Thanks, also `Compose` version is out of date too.

**Comment by simonschoelly** [comment]
Is that something that is blocking you or maybe someone else? Otherwise I might want to wait a bit and merge other things before immediately creating a new patch version.

**Comment by chakravala** [comment]
It's just something I noticed, not necessarily highly urgent.

**Comment by Affie** [comment]
Perhaps installing https://github.com/JuliaRegistries/CompatHelper.jl will help with the maintenance? I'm having compact issues with Compose.jl requiring v0.9 form another package.

**Comment by simonschoelly** [comment]
> Perhaps installing https://github.com/JuliaRegistries/CompatHelper.jl will help with the maintenance? I'm having compat issues with Compose.jl requiring v0.9 form another package.
> I'm ok working on master, so no need to tag a new version immediately.

Thanks, I decided to give this a try and added CompatHelper now.

I have also now upgraded the Compose dependency version to `0.8, 0.9` in the master branch: #126
