### ISSUE TITLE
Pleasa add option to change size

### ISSUE THREAD

**Issue by majsterkovic** [JuliaGraphs/GraphPlot.jl#147]
```julia
gplot(g, size = (600, 800))

**Comment by hdavid16** [comment]
You could also set the size when saving the plot using `draw` (https://github.com/JuliaGraphs/GraphPlot.jl#save-to-figure)

**Comment by hdavid16** [comment]
Alternately, could potentially update the `gplot` Compose object so that the UnitBox is set by `size`. Haven't tested this though.

**Comment by hdavid16** [comment]
see #133

**Comment by hdavid16** [comment]
@majsterkovic you can use GraphMakie, where you can set the size of your plot using Makie (e.g., `Figure(resolution = (600,800))`

**Comment by etiennedeg** [comment]
Closed by #186
