### ISSUE TITLE
allow `gplot` to set `seed` for `spring_layout`

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaGraphs/GraphPlot.jl#153]
I often need to redraw the same graph (via spring layout) multiple times but with different colors on the nodes. 

an optimal argument `seed` to allow me to set the seed inside `spring_layout` would be helpful so the layout doesn't change each time I re-run `gplot`.

currently, I must do:
```julia
using Random
Random.seed!(97330)
gplot(my_graph)
```

**Comment by afternone** [comment]
You can give the location of nodes to `gplot` as follows:
```julia
loc_x, loc_y = spring_layout(g)
gplot(g, loc_x=loc_x, loc_y=loc_y)
```

**Comment by SimonEnsemble** [comment]
thanks. the above didn't work for me, but this does:
```julia
loc_x, loc_y = spring_layout(graph, 97330) # seed is 97330

gplot(graph, loc_x, loc_y)
```
