### ISSUE TITLE
Node connected to itself with default lifestyle looks not great.

### ISSUE THREAD

**Issue by NAThompson** [JuliaGraphs/GraphPlot.jl#160]
(Firstly this library is awesome, so hopefully this doesn't come across as ungracious.)

If a node is connected to itself in a graph with the default `linetype`, the graph looks weird. However, if `linetype=curve`, then the graph looks great yet again.

Proposing to default the `linetype` to `curve` for an edge which originates and ends with the same node.

**Comment by hdavid16** [comment]
@NAThompson thank you for this feedback. This is fixed in PR #186, which will hopefully be reviewed someday and merged.
