### ISSUE TITLE
Doesn't plot, writes Compose.Context

### ISSUE THREAD

**Issue by FalkoSp** [JuliaGraphs/GraphPlot.jl#187]
Hi, with Julia 1.8, under Windows 10, 

    using GraphPlot
    using Graphs: smallgraph
    g = smallgraph(:karate)
    gplot(g)

doesn't plot anything, but writes a Compose.Context to standard out.

What am I doing wrong?

Thank you!

(graphs) pkg> status
Status `C:\graphs\Project.toml`
  [336ed68f] CSV v0.10.4
  [5ae59095] Colors v0.12.8
  [a93c6f00] DataFrames v1.3.4
  [a2cc645c] GraphPlot v0.5.2
  [86223c79] Graphs v1.7.2
  [47aef6b3] SimpleWeightedGraphs v1.2.1
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random

**Comment by afternone** [comment]
See #144

**Comment by FalkoSp** [comment]
Haha.
Thank you!

Maybe this should be made a bit more prominent in readme and doc :-)
