### ISSUE TITLE
discussion: deprecate Graphs.jl compatibility

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/GraphPlot.jl#19]
Graphs.jl itself is now part of JuliaArchive, and it's a fairly heavy dependency. I'd like to propose that we tag a final version that has Graphs.jl compatibility and then remove it from `REQUIRE`.

Thoughts?

**Comment by juliohm** [comment]
I second the proposal. LightGraphs.jl has become the defacto standard in Julia.

**Comment by afternone** [comment]
I quite agree.

**Comment by sbromberger** [comment]
I will put together a PR in the next few days then. Also need to remember whether we tagged a version already. I think we did.
