### ISSUE TITLE
Bad displays

### ISSUE THREAD

**Issue by Lecrapouille** [JuliaGraphs/GraphPlot.jl#190]
Hi ! Again to disturb you. Here is my matrix:

```
A = [3 7; 2 4]
```
Which corresponds to the expected network.
![Expected](https://user-images.githubusercontent.com/17874458/196570846-cfaebe42-a88b-4f48-882a-8d5573c14b63.png)

The following code
```
G = SimpleWeightedDiGraph(A)
gplot(G, nodelabel=1:nv(G), edgelabel=B)
```

gives me:
![Obtained1](https://user-images.githubusercontent.com/17874458/196570958-5d69be85-0c2c-4053-b2b6-5acc8806473e.png)

Issues are:
- no edge labels on nodes cycling to themselves,
- and in jupyter notebook the layout is truncated.

Based on https://github.com/JuliaGraphs/GraphPlot.jl/issues/160 The following code
```
gplot(G, nodelabel=1:nv(G), edgelabel=B, linetype="curve")
```
gives me:
![Obtained2](https://user-images.githubusercontent.com/17874458/196571194-0d57b499-7def-484a-a423-f93b87dac3ba.png)

There are:
- no edge labels on nodes cycling to themselves,
- and in jupyter notebook the layout is truncated.
- labels does not follow edges.
- edgelabeldistx and edgelabeldisty do not fix.

I dunno if https://github.com/JuliaGraphs/GraphPlot.jl/pull/186 will fix this simple graph.

**Comment by hdavid16** [comment]
Thanks for pointing these out. #186 will allow you to make a plot like the first one with straight edges for the non-self loops, and curved edges for the self loops. The cut out can be fixed in the PR as well because you can add margins to ensure the curved edges are fully shown. 

However, the edge labels on curved edges don't work as expected. Thanks for pointing this out. I'll see if we can get curved edge labels to work.

**Comment by hdavid16** [comment]
@Lecrapouille,

I just stumbled upon [GraphMakie.jl](https://graph.makie.org/dev/), which seems to be more actively developed and has better support for curved edges. Here is your example in GraphMakie

```julia
using Graphs, GraphMakie, CairoMakie

B = [3 7; 2 4]
g = SimpleDiGraph(B)
graphplot(g,
    layout = g -> [Point(-1,0), Point(1,0)],
    nlabels = string.("node ",1:nv(g)),
    elabels = string.([B[src(e),dst(e)] for e in edges(g)]), 
    elabels_rotation=0, 
    arrow_shift=0.99, 
    curve_distance = 0.1, 
    selfedge_size=1,
    selfedge_width=pi/9
)
```

This will produce the plot:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/9156129/213974907-ec86b16b-9a30-40f8-a392-5e281d7e081a.png">

You can of course do much more customization on the appearance if you want. Now the edge labels will be in the right place.

**Comment by Lecrapouille** [comment]
@hdavid16 Thanks you I'll give a try.

**Comment by hdavid16** [comment]
@Lecrapouille, I've added a commit to the PR #186 that will produce the following. This should fix the bug on the edge labels for curved edges.

```julia
B = [3 7; 2 4]
g = SimpleDiGraph(B)
gplot(g, [-1.,1.], [0.,0.],
    nodelabel=1:nv(g),
    edgelabel=B,
    linetype="curve",
    EDGELINEWIDTH=1,
    outangle=-pi/3,
    pad=5mm
)
```

<img width="278" alt="image" src="https://user-images.githubusercontent.com/9156129/214220172-8c3d5b05-f2e3-4ca5-b5b4-4c4cb20743f1.png">
