### ISSUE TITLE
Edgelabels attached to the wrong edges

### ISSUE THREAD

**Issue by colbec** [JuliaGraphs/GraphPlot.jl#192]
With Julia 1.8.3 Official release on openSUSE Leap 15.4 and Gnome:

With the following Julia code (uploaded as txt) I attempt to create a graph with 6 nodes and 4 edges. I assign random real values as weights to the edges. The adjacency matrix is created correctly but the attempt to use the edge weights as edge labels is only correct about 50% of the time. The weights are always correct, but as labels they are frequently attached to the wrong edges in the plot.

The last run produced the attached image and this output:

```
julia> thetest()
1, 5, 0.89
2, 5, 0.67
3, 4, 0.68
4, 5, 0.51
```
I believe this may be an issue, but also my coding may not be appropriate. I'm working on it.

[edgetest.jl.txt](https://github.com/JuliaGraphs/GraphPlot.jl/files/10295255/edgetest.jl.txt)
![thetest](https://user-images.githubusercontent.com/14130995/209342267-c9668c2f-1033-4323-aba6-5258e58e40c3.png)

**Comment by colbec** [comment]
Two additional observations:

1. In another open issue it is noted that all grouped variables need to be the same type when passed to Compose, so I changed the `edgecolors` to a vector consisting of all `colorant"lightgreen"` but this did not ease the problem.
2. One thing that seems consistent is that the first run of the script after Julia is up and running labels the edges correctly, but subsequent runs contain errors. This is a major problem in a Julia context since it means that repeated runs of the script must reload all the items in `using` all over again which is very painful.

**Comment by hdavid16** [comment]
Hi @colbec,

Your issue is that your GraphPlot.jl iterates through `edges(G)` when assigning edge labels. Your vector `edgeweights` is not always in the same order as `edges(G)`, which is what causes the labels to be placed on the edges you are not expecting. Here is a version of your code that should fix this problem (NOTE: you should avoid sharing code as an external file and just use GitHub's code insertion feature (i.e., add ```julia at the top of the code and end with ```, and paste the code with the rest of your text)):

```julia
using Graphs, SimpleWeightedGraphs, GraphPlot
using Random, Compose, Colors, Combinatorics
using Graphs, SimpleWeightedGraphs, GraphPlot
import Cairo, Fontconfig

function thetest()
	num_v = 6
	num_e = 4
	G = SimpleWeightedGraph()
	add_vertices!(G, num_v)
	labels = collect(1:num_v)
	nodecolors = rand(RGB{Float64},num_v)
	edgecolors = colorant"lightgreen"
	edgecombs = sort!(shuffle!(collect(combinations(1:num_v,2)))[1:num_e])
	# edgeweights = []
	for i in 1:num_e
		wt = round(max(rand(),0.1),digits=2)
		(x,y) = edgecombs[i]
		add_edge!(G, x, y, wt)
		println("$x, $y, $wt")
		# push!(edgeweights,wt)
	end
	draw(
		PNG("thetest.png",20cm,20cm), 
		gplot(G,nodelabel=labels,
			layout=stressmajorize_layout, 
			nodefillc=nodecolors,
			edgelabel=[G.weights[src(e),dst(e)] for e in edges(G)],#edgeweights,
			edgestrokec=edgecolors
		)
	)
    
    return G
end
```

**Comment by colbec** [comment]
Indeed this solves my issue. Thanks.
