### ISSUE TITLE
Conditional dependencies?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/GraphPlot.jl#2]
It seems strange to REQUIRE LightGraphs and Graphs when in all likelihood people will want to use this great package for either one or the other. Could I recommend something along the lines of what we do in LightGraphs for conditional dependencies?

```
try
    using LightGraphs
    nothing
catch
end
```
then you can have 
```
if isdefined(:LightGraphs)
...
```
for the LG specific code, repeating for Graphs.jl as necessary.

**Comment by afternone** [comment]
Can we close this issue?
