### ISSUE TITLE
Visualization issue with sparse graphs

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/GraphPlot.jl#20]
``` julia
using LightGraphs
G = Graph(8,1)
gplot(G)
```

![screenshot from 2016-10-12 15-18-46](https://cloud.githubusercontent.com/assets/3345261/19329826/aa3c7640-908f-11e6-9d9d-f8aeaa80f88b.png)

No edge is shown because the nodes are overlapping.

**Comment by sbromberger** [comment]
What happens if you use a different layout?

`function gplot(G; layout::Function=spring_layout, keyargs...)`

**Comment by juliohm** [comment]
Circular layout works fine for instance:

![screenshot from 2016-10-12 17-21-52](https://cloud.githubusercontent.com/assets/3345261/19332398/720db46c-90a0-11e6-9992-7140043fd7bf.png)

**Comment by juliohm** [comment]
Should this issue with the default layout be fixed or it is just a matter of choosing a more appropriate layout?

**Comment by jpfairbanks** [comment]
I guess you might want the edges to be drawn on top of the vertices? Would that make it a mess?

**Comment by juliohm** [comment]
That would be a better visualization than the current for sure :+1:

**Comment by juliohm** [comment]
Actually, rethinking about this issue, I believe edges on top is not the best visual. I will close the issue since it is not a bug, just a matter of choosing a better layout algorithm.
