### ISSUE TITLE
Subplots?

### ISSUE THREAD

**Issue by piperod** [JuliaGraphs/GraphPlot.jl#22]
I would like to create a figure with several graphs. Does GraphPlot support anything like subplot?

**Comment by sbromberger** [comment]
Not sure what functionality you're looking for, but you might try "combining" the graphs so that they're effectively disconnected components of a larger graph. That is:

```
julia> g = CompleteGraph(3)
{3, 3} undirected graph

julia> h = PathGraph(4)
{4, 3} undirected graph

julia> j = blkdiag(g,h)
{7, 6} undirected graph
```

**Comment by afternone** [comment]
@piperod There are no subplots function in GraphPlot. You can do subplots like this:
```julia
using GraphPlot
using Compose
using LightGraphs

g1 = CompleteGraph(10)
g2 = PathGraph(10)
g3 = barabasi_albert(10,3)
g4 = StarGraph(10)

compose(context(),
(context(0, 0, 0.5, 0.5), gplot(g1)),
(context(0.5, 0, 0.5, 0.5), gplot(g2)),
(context(0, 0.5, 0.5, 0.5), gplot(g3)),
(context(0.5, 0.5, 0.5, 0.5), gplot(g4)))

# add titles
compose(context(),
(context(0, 0, 0.5, 0.05), text(0.5,0,"complete graph",hcenter,vtop)),
(context(0, 0.05, 0.5, 0.45), gplot(g1)),
(context(0.5, 0, 0.5, 0.05), text(0.5,0,"path graph",hcenter,vtop)),
(context(0.5, 0.05, 0.5, 0.45), gplot(g2)),
(context(0, 0.5, 0.5, 0.05), text(0.5,0,"scale-free graph",hcenter,vtop)),
(context(0, 0.55, 0.5, 0.45), gplot(g3)),
(context(0.5, 0.5, 0.5, 0.05), text(0.5,0,"star graph",hcenter,vtop)),
(context(0.5, 0.55, 0.5, 0.45), gplot(g4)))
```
For more information, please refer to [Compose.jl](https://github.com/GiovineItalia/Compose.jl)

**Comment by hdavid16** [comment]
Have you tried @afternone 's solution?

**Comment by duodenum96** [comment]
Yes, but compose doesn't support regular plots generated by for example 

p1 = plot(...)

**Comment by hdavid16** [comment]
Then I believe the answer to your original question is no. You could save your GraphPlot plot to an image file and then try to use it in a subplot in Plots.jl or Makie.jl.

**Comment by duodenum96** [comment]
Thanks nonetheless and thanks for the great package!
