### ISSUE TITLE
Directed Graphs edgelabels fix?

### ISSUE THREAD

**Issue by AndyGreenwell** [JuliaGraphs/GraphPlot.jl#23]
This [commit](https://github.com/JuliaGraphs/GraphPlot.jl/commit/ab1b9444e056a6e9d87b9b91617ee8e99eda08e1) modified the placement of edge labels for directed graphs such that the edge label location cannot be altered by the end user.  Can this change be reverted such as to allow for the placement of edge labels to still be controlled by the `edgelabeldistx` and `edgelabeldisty` arguments?

**Comment by sbromberger** [comment]
I'm pretty sure this was inadvertent, in that the `+ edgelabeldistx*NODESIZE` should be applied regardless of whether the graph is directed, right?

**Comment by AndyGreenwell** [comment]
Seems that this change was a result of the following discussion: 

https://github.com/JuliaGraphs/GraphPlot.jl/issues/4

I would vote for applying `+ edgelabeldistx*NODESIZE` regardless of the graph being directed or undirected, which was the prior behavior.

**Comment by sbromberger** [comment]
I'm going to leave this for @afternone since I'm really not comfortable modifying layout code I don't understand :)
