### ISSUE TITLE
remove graphfamous?

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/GraphPlot.jl#27]
I don't think a plotting package is the right place for this
https://github.com/JuliaGraphs/GraphPlot.jl/blob/master/src/graphio.jl

Maybe move it to LighGraphs? @sbromberger @afternone 

Both the functions `graphfamous` and `readedgelist` should be removed

**Comment by afternone** [comment]
I agree with you. These functions are just for the convenience of me. They should be separated from the package.

**Comment by sbromberger** [comment]
We can move them into LightGraphs or LGE - we're planning on some major changes in the next couple of weeks anyway.

**Comment by juliohm** [comment]
@sbromberger is graphfamous integrated in LG already?

**Comment by sbromberger** [comment]
graphfamous isn't in yet, but I have a PR pending for reading in an edge list. Just needs work approval.

**Comment by simonschoelly** [comment]
`graphfamous` has been deprecated a while ago and at least the karate graph was moved to LightGraphs, so I am closing this issue.
