### ISSUE TITLE
add Erdos support

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/GraphPlot.jl#28]
I'd like to add Erdos support to GraphPlot. The implementation is kinda trivial but there is a design decision I would like to discuss with @afternone @jpfairbanks @sbromberger before I file a PR. 
Up to few days ago, when both Graphs and LightGraphs where supported, they where both required and imported by GraphPlot. We could do the same with Erdos and LG, also dependencywise it wouldn't be a burden since most dependence are in common, but I think that a cleaner design for GraphPlot would be to have it depend on no package:

```julia
try
     import LightGraphs
catch
    println("LightGraphs not installed. Once installed, execute the command `Base.compilecache(\"GraphPlot\")` 
   to activate plotting functionalities for LightGraphs.")
end
try
     import Erdos
catch
    println("Erdos not installed. Once installed, execute the command `Base.compilecache(\"GraphPlot\")` 
   to activate plotting functionalities for Erdos.")
end

if !isdefined(:Erdos) && !isdefined(:LightGraphs)
   warn("No supported graph package installed.")
end

if isdefined(:LightGraphs)
_nv(g::LightGraphs.SimpleGraph) = LightGraphs.nv(g)
_ne(g::LightGraphs.SimpleGraph) = LightGraphs.ne(g)
_vertices(g::LightGraphs.SimpleGraph) = LightGraphs.vertices(g)
_edges(g::LightGraphs.SimpleGraph) = LightGraphs.edges(g)
_src_index(e::LightGraphs.Edge, g::LightGraphs.SimpleGraph) = LightGraphs.src(e)
_dst_index(e::LightGraphs.Edge, g::LightGraphs.SimpleGraph) = LightGraphs.dst(e)
_adjacency_matrix(g::LightGraphs.SimpleGraph) = LightGraphs.adjacency_matrix(g)
_is_directed(g::LightGraphs.SimpleGraph) = LightGraphs.is_directed(g)
_laplacian_matrix(g::LightGraphs.SimpleGraph) = LightGraphs.laplacian_matrix(g)
end
....
```
What do you think?

**Comment by sbromberger** [comment]
@CarloLucibello - I have no objections if @afternone wants to support Erdos, but I am against removing any support of LightGraphs as long as the package remains in the JuliaGraphs organization.

**Comment by CarloLucibello** [comment]
could you clarify? I'm not saying LG support should be removed... I'm proposing a conditional compilation scheme

**Comment by sbromberger** [comment]
> I think that a cleaner design for GraphPlot would be to have it depend on no package:

I am not eager to change GraphPlot's dependency on LightGraphs. We brought it into JuliaGraphs specifically because it was our go-to plotting package, and LightGraphs is what most of the users are using. To make it conditional means that there will be an extra step for users who want to plot graphs, and I don't think it's worth making them jump through hoops to get their work done.

**Comment by CarloLucibello** [comment]
I don't agree with you, as usual :) 

>To make it conditional means that there will be an extra step for users who want to plot graphs, and I don't think it's worth making them jump through hoops to get their work done.

People who want to plot graphs usually hava a graph to plot, meaning that they already have LG installed. In the case they don't, which I fail to see how comes into being, and they `Pkg.add("GraphPlot")`, then they are clearly pointed `Pkg.add("LightGraphs"); Pkg.compilecache("GraphPlot")`. To do this once doesn't seem like jumping through hoops to me, and actually gives some indication on where to look for building the graphs you would like to plot.

**Comment by jpfairbanks** [comment]
Can't you just overload these functions to work on the Erdos.Graph type?

```
_nv(g::LightGraphs.SimpleGraph) = LightGraphs.nv(g)
_ne(g::LightGraphs.SimpleGraph) = LightGraphs.ne(g)
_vertices(g::LightGraphs.SimpleGraph) = LightGraphs.vertices(g)
_edges(g::LightGraphs.SimpleGraph) = LightGraphs.edges(g)
_src_index(e::LightGraphs.Edge, g::LightGraphs.SimpleGraph) = LightGraphs.src(e)
_dst_index(e::LightGraphs.Edge, g::LightGraphs.SimpleGraph) = LightGraphs.dst(e)
_adjacency_matrix(g::LightGraphs.SimpleGraph) = LightGraphs.adjacency_matrix(g)
_is_directed(g::LightGraphs.SimpleGraph) = LightGraphs.is_directed(g)
_laplacian_matrix(g::LightGraphs.SimpleGraph) = LightGraphs.laplacian_matrix(g)
```
Everything else in the package appears not to use any feature from LG.

**Comment by CarloLucibello** [comment]
yes, that's the idea in either case, maybe it was not completely clear from the first post. What I was asking there is 
1) should I add those interface methods and add Erdos to REQUIRE(like it was done for Graphs and LightGraphs)?

or

2) should I add those interface methods and put them behind those `try` and `isdefined` guards, and the interface for LG as well? 

I favour 2), but if you people prefer 1) and @afternone is ok to adding Erdos support to GraphPlot I'll go with that

**Comment by juliohm** [comment]
I don't think we should support different graph libraries, the code becomes hard to maintain that way. There are other alternative solutions with the PlotRecipes.jl framework that you may find interesting @CarloLucibello in case you need a custom plot for your package.

My vote is to close this issue and focus on improving GraphPlots.jl for better integration with LG only.
