### ISSUE TITLE
SVG missing in LG tutorials

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/GraphPlot.jl#29]
For some reason, some of the SVG generated by GraphPlot.jl are not appearing in the notebook online:

https://github.com/JuliaGraphs/JuliaGraphsTutorials/blob/master/Basics.ipynb

I am not sure this is an issue in the GraphPlot.jl package or an issue of the visualization feature of GitHub. The notebook shows correctly on my laptop locally.

@afternone do you have a guess of what may be happening? I don't want to interrupt you too much, I know you are about to defend your thesis.

**Comment by afternone** [comment]
Please visit [this nbviewer link](https://nbviewer.jupyter.org/github/JuliaGraphs/JuliaGraphsTutorials/blob/master/Basics.ipynb). It seems all right.

**Comment by juliohm** [comment]
That is interesting, I will report the issue on GitHub somewhere.
