### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/GraphPlot.jl#35]
Could you please tag a new version? The latest tag is not functioning with the latest LG tag.

**Comment by sbromberger** [comment]
is the current master working with 0.6 and LightGraphs v0.8+?

**Comment by juliohm** [comment]
I tested master on Julia v0.5. I cannot switch to Julia v0.6 yet (unfortunately), many dependencies are not working.

**Comment by sbromberger** [comment]
when you say "not functioning with the latest LG tag", are you referring to something in the 0.7.x range (since nothing later will work on 0.5)?

**Comment by juliohm** [comment]
Sorry, I should have been more precise, this is the combination that is working:

```julia
julia> Pkg.status("LightGraphs")
 - LightGraphs                   0.7.7

julia> Pkg.status("GraphPlot")
 - GraphPlot                     0.1.0+             master
```

**Comment by sbromberger** [comment]
see also #33.

**Comment by sbromberger** [comment]
If you can hold off, I'd like to see whether we can get #33 merged first.

**Comment by juliohm** [comment]
Thanks Seth, no rush at all. I am able to move with work using master.

**Comment by juliohm** [comment]
We should be good to go after #41 is merged.

**Comment by sbromberger** [comment]
Thanks for sticking with this, @juliohm.

**Comment by juliohm** [comment]
Should we tag a new version now or you still have other features coming?

**Comment by sbromberger** [comment]
I'm done. I think we should tag.

**Comment by sbromberger** [comment]
Er, wait. Perhaps we should bump up the Julia version in `REQUIRES` first?
