### ISSUE TITLE
GraphPlot package isn't loading when debugging

### ISSUE THREAD

**Issue by Chathanee** [JuliaGraphs/GraphPlot.jl#36]
Hi,  I'm using the GraphPlot package in my Julia program. I added that to Julia and even updated it several times.I checked whether the required **GraphPlot.ji** is in **/Users/user/.julia/lib/v0.5**. But it's located in the following path.  **/Users/user/.julia/v0.5/GraphPlot/src.**

Is there anything that we could do to fix this one? The following is the error message that I'm getting when running the code. 
----------------------------------------------------------------------------------------------------
`LoadError: Failed to precompile GraphPlot to /Users/user/.julia/lib/v0.5/GraphPlot.ji.
while loading /Users/user/Dropbox/P/M/ip.jl, in expression starting on line 5
 in compilecache(::String) at loading.jl:593
 in require(::Symbol) at loading.jl:422
 in require(::Symbol) at sys.dylib:?
 in include_string(::String, ::String) at loading.jl:441
 in include_string(::String, ::String) at sys.dylib:?
 in include_string(::Module, ::String, ::String) at eval.jl:34
 in (::Atom.##59#62{String,String})() at eval.jl:73
 in withpath(::Atom.##59#62{String,String}, ::String) at utils.jl:30
 in withpath(::Function, ::String) at eval.jl:38
 in macro expansion at eval.jl:71 [inlined]
 in (::Atom.##58#61{Dict{String,Any}})() at task.jl:60
`

**Comment by sbromberger** [comment]
What is the specific error if you do a `using GraphPlot` in the REPL?

**Comment by Chathanee** [comment]
It says `LoadError: Failed to precompile GraphPlot `

**Comment by sbromberger** [comment]
Can you please paste the full error from the repl?

**Comment by Chathanee** [comment]
It's the same as I indicated in my question. 

`LoadError: Failed to precompile GraphPlot to /Users/user/.julia/lib/v0.5/GraphPlot.ji. while loading /Users/user/Dropbox/P/M/ip.jl, in expression starting on line 5`

`Line 5` indicates the line `using GraphPlot`

**Comment by Beatzekatze** [comment]
Don't know if the issue has the same origin, but I have an issue with precompiling GraphPlots as well. The error arises when directly `using GraphPlot` or `import GraphPlots` in a fresh Julia session. LightGraphs is not (actively) imported by me before importing GraphPlot, all packages are up to date according to Pkg.status(). 
(GraphPlot 0.1.0, LightGraphs 0.7.7, Graphs 0.7.1; obviously GraphPlot and LightGraphs have an issue  with each other) 

` WARNING: both Graphs and LightGraphs export "AbstractGraph"; uses of it in module GraphPlot must be qualified

ERROR: LoadError: UndefVarError: AbstractGraph not defined
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Users/xxx/Applications/julia/usr/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Users/xxx/Applications/julia/usr/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
 in _start() at /Users/xxx/Applications/julia/usr/lib/julia/sys.dylib:?
while loading /Users/xxx/.julia/v0.5/GraphPlot/src/GraphPlot.jl, in expression starting on line 56`

**Comment by sbromberger** [comment]
@Chathanee please follow my earlier request: I'd like the full output of `using GraphPlot` from within the REPL, not the output you get when you run your script.

**Comment by sbromberger** [comment]
@Beatzekatze what happens if you switch to GraphPlot master via `Pkg.checkout`?

**Comment by Beatzekatze** [comment]
@sbromberger that fixes the problem, thanks!

**Comment by sbromberger** [comment]
@Chathanee do you have an update for this issue? Thanks.

**Comment by Chathanee** [comment]
@sbromberger I removed the Graphs package from my code. I'm still fixing the error in my code now. It's working now, but I'm getting the following error. 
```

LoadError: BoundsError: attempt to access 5-element Array{Int64,1} at index [9]
while loading /Users/cjayathilake/Dropbox/Python/Model/ip.jl, in expression starting on line 56
in anonymous at base/<missing>
in macro expansion; at ip.jl:110
in maximum_flow at LightGraphs/src/flow/maximum_flow.jl:181
in #maximum_flow#133 at LightGraphs/src/flow/maximum_flow.jl:184
in push_relabel at LightGraphs/src/flow/push_relabel.jl:32`
```

**Comment by sbromberger** [comment]
This is the graphplot issue you created, not the one with `add_edge!` (which is https://github.com/JuliaGraphs/LightGraphs.jl/issues/662). I had asked you in this issue to paste the full output of `using GraphPlot`.

**Comment by Chathanee** [comment]
@sbromberger For this too I removed the graph-lot package and recoded.

**Comment by sbromberger** [comment]
So do you no longer have this issue with GraphPlot? If not, I'll go ahead and close this out.

**Comment by Chathanee** [comment]
No. Will talk to you if I'll have to use it in the future.
