### ISSUE TITLE
Duplication of code plot.jl and plot_test.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/GraphPlot.jl#40]
@afternone, could you please explain the file `plot_test.jl`? Was it copied from `plot.jl` with a few small changes? Can we get rid of it?

**Comment by afternone** [comment]
Yes, it's ok to remove the file `plot_test.jl` and the related function `gplot1` in the file `GraphPlot.jl`. I'll fix it later.

**Comment by juliohm** [comment]
Thank you @afternone , I have erased the references in GraphPlot.jl, please let me know if I can remove the file plot_test.jl itself. Could you please review/merge #41 meanwhile?

**Comment by juliohm** [comment]
Deleted plot_test.jl in #45 , closing this issue.
