### ISSUE TITLE
Remove plot_test.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/GraphPlot.jl#43]
Can we remove `plot_test.jl` from the project? It seems that it was copied from `plot.jl` and slightly modified for...?

Please let me know if I can proceed and I will submit a PR with the deletion.

**Comment by sbromberger** [comment]
See https://github.com/JuliaGraphs/GraphPlot.jl/issues/40#issuecomment-310881569 - I think it's ok.

**Comment by juliohm** [comment]
From that comment I understood that we can erase the reference to the file in GraphPlot.jl. Can we also delete the file from the project?

**Comment by sbromberger** [comment]
>  it's ok to remove the file `plot_test.jl`

seems to be what you're looking for.

**Comment by juliohm** [comment]
Yes, it must be it, I will remove the file, bump up the version in the REQUIRE and send the PR.
