### ISSUE TITLE
I wrote a utility that uses graphplot - useful for macs with iterm

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/GraphPlot.jl#44]
Hi,

Now that @juliohm has fixed some graphplot stuff, it works again in the REPL. If you have a mac and iterm with the iterm shell extensions installed, you can use `graphcat` to display a graph in repl. This uses Plots, which gives a different view of the graph than GraphPlot.

If you have iterm with TerminalExtensions, `gcat` will give you the GraphPlot view which (IMO) is a bit nicer. Screenshots attached.

You can download the code by cloning https://github.com/sbromberger/MiscGraphUtils.jl.

<img width="526" alt="screen shot 2017-06-25 at 11 52 37" src="https://user-images.githubusercontent.com/941359/27518793-db5a3f56-599c-11e7-9698-867ae521ede1.png">
<img width="417" alt="screen shot 2017-06-25 at 11 52 48" src="https://user-images.githubusercontent.com/941359/27518795-db954178-599c-11e7-9748-f8a372c494a2.png">

**Comment by juliohm** [comment]
We should be good to tag a new version for GraphPlot.jl? All tests are passing and I don't have warnings locally on Julia v0.6 :+1:

**Comment by sbromberger** [comment]
Closing this out since v0.2.0 is working.
