### ISSUE TITLE
Failure to compile GraphPlot

### ISSUE THREAD

**Issue by nil-8** [JuliaGraphs/GraphPlot.jl#49]
When I try to compile GraphPlot, I get the following error.

Is this the correct place to report this, and is there a simple way to resolve? I tried removing either LightGraphs or Graphs packages, but GraphPlot seems to depend on both so it seems like a catch-22.

Possibly this is just because I am using Julia v0.5 and I should be using Julia v0.6.

> julia> using(GraphPlot)
> INFO: Precompiling module GraphPlot.
> WARNING: Method definition open_file(Any) in module GraphPlot at  /home/.../.julia/v0.5/GraphPlot/src/plot.jl:229 overwritten at  /home.../.julia/v0.5/GraphPlot/src/plot_test.jl:297.
> WARNING: both Graphs and LightGraphs export "AbstractGraph"; uses of it in module GraphPlot must be qualified
>ERROR: LoadError: UndefVarError: AbstractGraph not defined

**Comment by sbromberger** [comment]
That indicates you're using an outdated version of LightGraphs. What version of Julia and LightGraphs do you have installed?

**Comment by sbromberger** [comment]
It also indicates you're using an outdated version of GraphPlot, if Graphs is still a dependency.

**Comment by nil-8** [comment]
Thank you. Yes, my software turned out to be outdated, most importantly trying to run this on Julia v 0.5. It is working now on Julia 0.6.
