### ISSUE TITLE
Problem with the tutorial

### ISSUE THREAD

**Issue by my-little-repository** [JuliaGraphs/GraphPlot.jl#55]
The following tutorial does not seem to work.
https://github.com/JuliaGraphs/GraphPlot.jl/blob/master/examples/graphplot.ipynb

I have executed the first two cells and I get the following errors.

     julia> using Graphs, GraphPlot
     Warning:[...]
     
     julia> g = simple_graph(3, is_directed=false)
     add_edge!(g, 1, 2)
     add_edge!(g, 2, 3)
     add_edge!(g, 3, 1)
     # just plot it
     gplot(g) 
     Undirected Graph (3 vertices, 0 edges)
     
     julia> edge [1]: 1 -- 2
     
     julia> edge [2]: 2 -- 3
     
     julia> edge [3]: 3 -- 1
     
     julia> 
     julia> ERROR: MethodError: no method matching _nv(::Graphs.GenericGraph{Int64,Graphs.Edge{Int64},UnitRange{Int64},Array{Graphs.Edge{Int64},1},Array{Array{Graphs.Edge{Int64},1},1}})
     Closest candidates are:
       _nv(!Matched::LightGraphs.AbstractGraph) at ~/.julia/v0.6/GraphPlot/src/GraphPlot.jl:41
     Stacktrace:
      [1] spring_layout(::Graphs.GenericGraph{Int64,Graphs.Edge{Int64},UnitRange{Int64},Array{Graphs.Edge{Int64},1},Array{Array{Graphs.Edge{Int64},1},1}}) at ~/.julia/v0.6/GraphPlot/src/layout.jl:99
      [2] #gplot#38(::GraphPlot.#spring_layout, ::Array{Any,1}, ::Function, ::Graphs.GenericGraph{Int64,Graphs.Edge{Int64},UnitRange{Int64},Array{Graphs.Edge{Int64},1},Array{Array{Graphs.Edge{Int64},1},1}}) at ~/.julia/v0.6/GraphPlot/src/plot.jl:224
      [3] gplot(::Graphs.GenericGraph{Int64,Graphs.Edge{Int64},UnitRange{Int64},Array{Graphs.Edge{Int64},1},Array{Array{Graphs.Edge{Int64},1},1}}) at ~/.julia/v0.6/GraphPlot/src/plot.jl:224

**Comment by sbromberger** [comment]
@my-little-repository GraphPlot.jl no longer supports Graphs.jl (hasn't for a while, actually). Can you use LightGraphs instead?

**Comment by sbromberger** [comment]
In general, though, the tutorial needs to be updated. Keeping this open to track.

**Comment by my-little-repository** [comment]
I tried with LightGraphs and it works. LightGraphs is not optimal for my use case though because I am dealing with labeled trees and I need to add/delete numerous nodes. The fact that the LightGraphs delete function does not preserve labels is a problem.

**Comment by sbromberger** [comment]
One thing I'd suggest is trying LightGraphs/MetaGraphs and putting your labels in the metadata. That will preserve them across deletes, but you'll need to use built-in filtering functions to identify the nodes.

Check out MetaGraphs.jl for more details.

**Comment by my-little-repository** [comment]
ok, thanks, I will check out MetaGraphs.

**Comment by simonschoelly** [comment]
If nobody objects, I will close this soon.

**Comment by sbromberger** [comment]
Why wait? Let's close it now. If anyone objects they can request a reopen. :)
