### ISSUE TITLE
Self-loops not correctly drawn

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/GraphPlot.jl#60]
At the moment self-loops are simpy drawn as an arrow pointing to the vertex. As far as I know, such a self loop is usually drawn like this: https://en.wikipedia.org/wiki/Loop_(graph_theory)#/media/File:6n-graph2.svg
It the current implementation on purpose or could this be changed?

**Comment by sbromberger** [comment]
It could definitely be changed. Self loops are a relatively late addition to LightGraphs and there are things that are undoubtedly broken. You found one of them :)

**Comment by simonschoelly** [comment]
Fixed by #90
