### ISSUE TITLE
get GraphPlot 1.0 ready

### ISSUE THREAD

**Issue by matbesancon** [JuliaGraphs/GraphPlot.jl#65]
Make GraphPlot usable from julia & LightGraphs 1.0

**Comment by timkittel** [comment]
:+1:

**Comment by sbromberger** [comment]
Closed by https://github.com/JuliaLang/METADATA.jl/pull/18449

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
