### ISSUE TITLE
Precompile and build error

### ISSUE THREAD

**Issue by anuraag94** [JuliaGraphs/GraphPlot.jl#68]
Julia newbie here. I apologize if this is noise, but I've read through some of the other issues listed here, and it seems like they're addressing the actual usage of the package. I used `pkg"add GraphPlot#master"` because I had errors when trying to install via Pkg.add, and that seemed to work. However, when I try to `using GraphPlot`, I get this error message:

```
 Info: Precompiling GraphPlot [a2cc645c-3eea-5389-862e-a155d0052231]
└ @ Base loading.jl:1186
ERROR: LoadError: LoadError: syntax: unsupported `const` declaration on local variable around /home/agirdhar/.julia/packages/GraphPlot/9WiLm/src/layout.jl:99
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /home/agirdhar/.julia/packages/GraphPlot/9WiLm/src/GraphPlot.jl:3
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:389
 [12] top-level scope at ./none:3
in expression starting at /home/agirdhar/.julia/packages/GraphPlot/9WiLm/src/layout.jl:64
in expression starting at /home/agirdhar/.julia/packages/GraphPlot/9WiLm/src/GraphPlot.jl:23

Failed to precompile GraphPlot [a2cc645c-3eea-5389-862e-a155d0052231] to /home/agirdhar/.julia/compiled/v1.0/GraphPlot/bUwXr.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
 [9] top-level scope at In[9]:25
```

I'm using Julia 1.0 in Jupyter with the most current version of LightGraphs. Any thoughts on this issue?

**Comment by simonschoelly** [comment]
The current master of `GraphPlot.jl` does not work with Julia v1.0 yet. There is an open PR that will fix this, but we have to wait for another package (Compose.jl) to tag a new version of their package.

If you want to plot your graps right now, there is another package called TikzGraphs.jl that uses LaTeX for rendering. This one works on 1.0, but might have some problems if your graph has too many vertices.

**Comment by boohbah94** [comment]
Thanks for the recommendation! I actually already tried TikzGraphs, but had some other issues with that. Maybe just LaTeX rendering issues that I can try to figure out. Are there no other options? Do you have any idea how long we'll have for Compose.jl?

**Comment by simonschoelly** [comment]
The issue is this one: GiovineItalia/Compose.jl#297,  I don't think it will take much longer.

You can of course always try to merge the already open PR, but that might be a bit much for a beginner.
I think there are some other plotting solutions for Julia, but I don't know how well they are maintained.
Maybe you can use graphviz for plotting. It's quite easy to write this format, here is a simple function that I was just working on:
```
function writedot(g::AbstractGraph, gname::AbstractString)
    graph_type = is_directed(g) ? "digraph" : "graph"
    edgeop = is_directed(g) ? "->" : "--"
    println("$graph_type $gname {")
    for e in edges(g)
        println("$(src(e)) $edgeop $(dst(e))")
    end
    println("}")
end
```
you can save the output with a `.dot` extension and open it with the application graphviz or just cp it here: http://www.webgraphviz.com/

Also the package GraphIO.jl can write some other formats (saddly no .dot yet), so you could do that and open it in graphviz or another program such as https://gephi.org/

**Comment by anuraag94** [comment]
I noticed the Julia 1.0 compatible version of Compose is now out, and your build is succeeding. However, I seem to be getting a similar precompile and build error as before

**Comment by anuraag94** [comment]
Sure:

```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
```

**Comment by sbromberger** [comment]
Did you mean to close this?

I'd make sure you've updated to the latest GraphPlot code. v0.3.0 should be your reported version number.

**Comment by anuraag94** [comment]
Ah, no I think I'd accidentally closed this, but thank you. I've tried to run `Pkg.update("GraphPlot")`, but the version remains the same. I think it's because I'd originally pulled it from the master branch at v0.2.1. Is there a way to go back to the regular package update command?

**Comment by sbromberger** [comment]
erm, I think all you have to do is `]free GraphPlot`.

**Comment by anuraag94** [comment]
I get this message when I try to do that. It seems like it's not able to see v0.3.0?

```
ERROR: Unsatisfiable requirements detected for package GraphPlot [a2cc645c]:
 GraphPlot [a2cc645c] log:
 ├─possible versions are: [0.1.0, 0.2.0-0.2.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0-0.2.1]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by sbromberger** [comment]
Looks like you might need to do an `]update` first.

**Comment by anuraag94** [comment]
Perfect, thank you!
