### ISSUE TITLE
Edge coloring?

### ISSUE THREAD

**Issue by anuraag94** [JuliaGraphs/GraphPlot.jl#70]
Is it possible to adjust the colors of the edges? I don't see it anywhere in the examples. If not, could this be a feature? I have an application where I'd like to change the weight or transparency of the edges, and it seems like something that would be generally useful.

**Comment by simonschoelly** [comment]
If you type in `?gplot` in the repl, it will show you all argument that you can pass to `gplot`. 
In your case, that would be `edgestrokec`, which can either be a single color or a vector that specifies the color for each edge. It is not clear to me at the moment which entry in the array corresponds to which edge, but I assume that the edges appear in lexical ordering.

**Comment by anuraag94** [comment]
Thank you!

**Comment by anuraag94** [comment]
Opening this up again - I ran a quick test to see if I could parse out the ordering, but it's still not too clear. What do you mean by lexical ordering? If I used LightGraphs to generate a graph from an adjacency matrix, would the first edge in the ordering be the edge corresponding to (1,2) or (2,1) if it exists?

**Comment by anuraag94** [comment]
Okay, that makes sense. I'll head over to there.
