### ISSUE TITLE
make default layout deterministic

### ISSUE THREAD

**Issue by stevengj** [JuliaGraphs/GraphPlot.jl#76]
The default `spring_layout` is non-deterministic, which doesn't seem desirable to me.  It seems better to do something like:

```jl
function deterministic_spring_layout(g::AbstractGraph; seed::Integer=0, kws...)
    rng = MersenneTwister(seed)
    spring_layout(g, 2 .* rand(rng, nv(g)) .- 1.0, 2 .* rand(rng,nv(g)) .- 1.0; kws...)
end
```

**Comment by sbromberger** [comment]
I'd be in favor of just replacing `spring_layout` with a deterministic (seeded) version. Would you mind making a PR?

**Comment by stevengj** [comment]
Sure.
