### ISSUE TITLE
Make Release

### ISSUE THREAD

**Issue by travigd** [JuliaGraphs/GraphPlot.jl#85]
I'd like to use #76 (deterministic spring layout) without telling my colleagues to install `GraphPlots#master`. That was the last change in almost four months, so I'd really appreciate a minor release.

Thanks for all your hard work!

**Comment by travigd** [comment]
Thank you, @simonschoelly !

**Comment by simonschoelly** [comment]
@matbesancon was actually the one who created the new `Project.toml`. But the JuliaRegistrator has not picked up this new version, so nothing has happened so far, and I don't think I have the necessary rights, to fix that.

**Comment by travigd** [comment]
Oh, I see. I think I was able to install it because I'd already cloned the project. Feel free to re-open then. In a fresh Julia install, I still get `v0.3.1`.
