### ISSUE TITLE
How can I control the output plot size in Juno's Plots pane?

### ISSUE THREAD

**Issue by AnselmJeong** [JuliaGraphs/GraphPlot.jl#94]
I've been using GraphPlot.jl in Juno IDE environment (add-on on ATOM).

The output from `gplot()` command in Juno's Plots pane is so small so that it is hard to identify node or edge labels.
Unlike ordinary output from `plot()` command, zoom in or zoom out options are disabled.
I cannot find any arguments in `gplot()` to control the overall size of the output plot. Do you know how?

```julia
g = graphfamous("karate")
gplot(g)
```
![image](https://user-images.githubusercontent.com/1776524/64470232-e03fbe80-d17a-11e9-8814-bbd86d4d0001.png)

Thanks in advance…

**Comment by lihebi** [comment]
+1 for controlling of graph size, I'm on IJulia jupyter-notebook backend

**Comment by simonschoelly** [comment]
As `GraphPlot` uses `Compose` internally, you could just change the default settings there:
```
julia> using Compose
julia> set_default_graphic_size(20cm,20cm)
```
That should make the drawing area bigger.

**Comment by hdavid16** [comment]
Might make sense to export `set_default_graphic_size` in GraphPlot and add this to the docs
