### ISSUE TITLE
Integrate possibility to save Graphs within GraphPlots

### ISSUE THREAD

**Issue by oskarpfeffer** [JuliaGraphs/GraphPlot.jl#95]
I wondered why you didn't include the possibility to save graphs within GraphPlots and instead make people use Compose externally. I think it would be quite useful.

**Comment by hdavid16** [comment]
Saving to SVG would be easy, just need to export `SVG` from compose
Saving to PDF of PNG requires Cairo and Fontconfig as dependencies...

So it depends on if the developers want to add extra deps
