### ISSUE TITLE
Tutorial examples not working

### ISSUE THREAD

**Issue by jzazo** [JuliaGraphs/GraphPlot.jl#97]
Trying the first lines of the readme file do not work:

```
using GraphPlot
using Graphs

g = graphfamous("karate")
nodelabel = [1:num_vertices(g)]
```
Gives error:
```MethodError: no method matching num_vertices(::LightGraphs.SimpleGraphs.SimpleGraph{Int64})
Closest candidates are:
  num_vertices(!Matched::GenericEdgeList) at /home/javier/.julia/packages/Graphs/GQCid/src/edge_list.jl:27
  num_vertices(!Matched::GenericAdjacencyList) at /home/javier/.julia/packages/Graphs/GQCid/src/adjacency_list.jl:36
  num_vertices(!Matched::GenericIncidenceList) at /home/javier/.julia/packages/Graphs/GQCid/src/incidence_list.jl:47
  ...
top-level scope at network_graph.jl:78
```

If I try:
```
nodesize = [Graphs.out_degree(v, g) for v in Graphs.vertices(g)]
gplot(g, nodesize=nodesize)
```
Gives error:
```
```MethodError: no method matching vertices(::LightGraphs.SimpleGraphs.SimpleGraph{Int64})
Closest candidates are:
  vertices(!Matched::GenericEdgeList) at /home/javier/.julia/packages/Graphs/GQCid/src/edge_list.jl:28
  vertices(!Matched::GenericAdjacencyList) at /home/javier/.julia/packages/Graphs/GQCid/src/adjacency_list.jl:37
  vertices(!Matched::GenericIncidenceList) at /home/javier/.julia/packages/Graphs/GQCid/src/incidence_list.jl:54
  ...
top-level scope at network_graph.jl:83
```

**Comment by sbromberger** [comment]
`Graphs.jl` is not being actively developed any more. We should update the example in the readme to use LightGraphs.

**Comment by sbromberger** [comment]
Ref #99

**Comment by anandijain** [comment]
None of the examples work still, at least for plotting in repl
First example just returns a very long type signature of `Compose.Context(...`
```using LightGraphs: smallgraph
g = smallgraph(:karate)
gplot(g)```
What can I do to plot graphs?

**Comment by matbesancon** [comment]
the way Compose and GraphPlot work is by constructing an object which describes the graph. The simplest way to display it is to use gplothtml which will open it in your browser, or to save the graph as svg / png and open it

**Comment by rodrigo-moreno** [comment]
I am still unable to run the lines in the tutorials. I have tried running the following code both in the REPL and in Jypyter, with the same error in both instances:
```
using LightGraphs
using GraphPlots

g = Graph(3, 2)
gplot(g)
```

The error I get says ```MethodError: no method matching spring_layout(::SimpleGraph{Int64})```. I tried using ```gplothtml``` instead, as suggested above, but it gives the same error.

I am on MacOS with Big Sur, with an M1 processor. The versions I installed for LightGraphs and GraphPlots are 1.3.5 and 0.5.0, respectively.

Please, if there is any other relevant information, let me know; this is my first time posting such a thing.

**Comment by AndreMacleod** [comment]
I am Having the same issue plotting MetaGraphs 
graph = MetaGraph(df, :reviewerID, :asin)
gplot(graph)
error message =  MethodError: no method matching spring_layout(::MetaGraph{Int64, Float64})

MetaGraphs v0.7.1
Graphs v1.4.1
GraphPlot v0.5.0

**Comment by cyrenehowland** [comment]
I am also having this issue and am using Jupyter on MacOS with Monterey with an M1 processor.

**Comment by thomasvilches** [comment]
Hi everyone!

I was having this issue when trying to plot a watts-strogatz network, and what worked for me was:

    ```
N = LightGraphs.watts_strogatz(1000,10,0.1) # created the network
    MM = LightGraphs.adjacency_matrix(N) #extracted the adjacency matrix
    gg = Graphs.SimpleGraph(MM) # created a SimpleGraph based on the adjacency Matrix
    gplot(gg) # Plot the network
```

**Comment by thomasvilches** [comment]
Hi everyone!

I was having this issue when trying to plot a watts-strogatz network, and what worked for me was:
`
N = LightGraphs.watts_strogatz(1000,10,0.1) # created the network
MM = LightGraphs.adjacency_matrix(N) #extracted the adjacency matrix
gg = Graphs.SimpleGraph(MM) # created a SimpleGraph based on the adjacency Matrix
gplot(gg) # Plot the network 

`

**Comment by etiennedeg** [comment]
`LightGraphs.jl` is now archived, you should use [`Graphs.jl`](https://github.com/JuliaGraphs/Graphs.jl). See [here](https://github.com/JuliaGraphs/Graphs.jl#transition-from-lightgraphs-to-graphs) how to make the transition
