### ISSUE TITLE
Nodesize label not working

### ISSUE THREAD

**Issue by jzazo** [JuliaGraphs/GraphPlot.jl#98]
I do not observe any difference in the node sizes when indicating node size:
```
using GraphPlot

g = graphfamous("karate")
gplot(g, nodesize=10)
```
vs.
```
gplot(g, nodesize=50)
```

How can this be fixed, it is a very important feature? Thank you.

**Comment by sbromberger** [comment]
The node sizes are relative to each other within a plot. Since for each graph you're giving each node the same size, they will plot the same. Try varying the node sizes within a graph.

**Comment by jzazo** [comment]
Is there a way to increase the node size of the vertices? I have near to 9k vertices but they are very tiny and the edges dominate the whole plot. Visualizing the vertices becomes difficult. Can this be fixed? Thank you.

**Comment by sbromberger** [comment]
You could add another vertex using `add_vertex!` and set that to have nodesize 1, and then set the others to something large, like 50 or 100. You won't see that small vertex.

But I have to say, if you're trying to visualize 9000 vertices (by color no less), you're probably doing something you shouldn't.

**Comment by jzazo** [comment]
Thanks. I set first node's size to 1, and the rest to 1e4, but node sizes still don't change, they are all still tiny.

I am plotting a nearest neighbors graph over 9k nodes, and I am not interested in the individual edges, but the underlying clusters.

**Comment by sbromberger** [comment]
what size is your plot? To plot 9k nodes with a noticeable 1000:1 size differential, you'd probably be measuring plotsize in meters / decameters.

This is what I meant in my earlier statement that "you're probably doing something you shouldn't" – except for very small graph sizes (that is, on the order of 1e2), if your problem requires visualization, you've already lost the game.

**Comment by jzazo** [comment]
Oh, I see. I am doing 10x10 cm. I will try other sizes.

**Comment by sbromberger** [comment]
so,  some quick math:

9000 vertices in 100 cm^2 = average 90 vertices per cm^2, which means that each vertex can have a MAX size of 0.1 mm, and even then they won't be differentiable.

**Comment by jzazo** [comment]
OK, thank you, now I get it. 

If the nodes could overlap, then the visualization could be helped a little better. They are densely clustered, as you say.

**Comment by sbromberger** [comment]
depending on what you need to show, you might consider clustering the vertices and then using "merge_vertices` to collapse the clusters into single vertices, and then plotting. Again, think ~100 vertices as opposed to thousands.

**Comment by jzazo** [comment]
Thank you Seth for your continuous help and suggestions. I think I finally figured it out. There a few non documented variables in the definition of `gplot`, and the relevant one is `NODESIZE=0.25 / sqrt(nv(g))`. I set it up to two times the default value, and that gives me perfect results. Some nodes overlap, but that is fine.

**Comment by sbromberger** [comment]
Awesome! I didn't think to change `NODESIZE` but glad to hear it worked for you.

**Comment by Hugo-Trentesaux** [comment]
I confirm, it works well with 1577 nodes and NODESIZE=0.1

![graph](https://user-images.githubusercontent.com/18427584/82152163-be492080-985f-11ea-96a1-92c4cbd2d898.png)
